### ISSUE TITLE
Problem aufter upgrade to Homeassistant 2022.7 

### ISSUE THREAD

**Issue by Delta1977** [rossdargan/lay-z-spa-component#13]
In HA 2022.7 arrived Python 3.10

there I got this error 
Logger: homeassistant.config_entries
Source: custom_components/layz_spa/__init__.py:39 
Integration: Lay-Z Spa 
First occurred: 15:52:35 (2 occurrences) 
Last logged: 17:32:26

Error setting up entry My Lay-Z-Spa for layz_spa
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/layz_spa/__init__.py", line 39, in async_setup_entry
    await hub.update_status()
  File "/usr/local/lib/python3.10/site-packages/layz_spa/spa.py", line 30, in update_status
    self.wave_appm_min = attr["wave_appm_min"]
KeyError: 'wave_appm_min'

**Comment by Delta1977** [comment]
mmh. after upgrade to HA 2022.7.1 it works again
